# Generated by Django 5.2.11 on 2026-05-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_create_default_water_bottle'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='change_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
